import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/components/global/Footer";
import { Navbar } from "@/components/global/Navbar";

import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RozgarDwar User",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />

        {/* ✅ ADD TOASTER HERE */}
        <Toaster position="top-right" reverseOrder={false} />

        {children}
        <Footer />
      </body>
    </html>
  );
}